"""add_otp_timestamp_to_user

Revision ID: 1a7ef76e5cc2
Revises: a45e8175d5e3
Create Date: 2026-07-11 11:47:33.950760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7ef76e5cc2'
down_revision: Union[str, Sequence[str], None] = 'a45e8175d5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_timestamp')
    # ### end Alembic commands ###
